import React, { useState } from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import MenuModal from '../../components/MenuModal';

export default function PrivacyPolicy(props) {
	const [isModalOpen, setIsModalOpen] = useState(false);

	const toggleModal = () => {
		setIsModalOpen(!isModalOpen);
	};

	return <div>
		<Header isModalOpen={isModalOpen} onPress={toggleModal} />
		<div className="flex flex-col items-center px-[16px] md:px-12">
			<div className="mt-8">
				<p className="text-5xl text-center font-semibold">Privacy Policy</p>
			</div>
			<div className="max-w-6xl flex flex-col">
				<div className="mt-12">
					<p>Creation International is serious about protecting your online privacy. This Privacy
						Statement explains our views and practices concerning privacy, and how they may pertain
						to you as a user of our website.</p>
				</div>
				<div className="mt-8">
					<p>Creation International (“us”, “we”, or “our”) operates the
						https://creationinternational.com/ website (the “Service”).
						https://creationinternational.com/ is serious about protecting your online privacy. This
						Privacy Statement explains our views and practices concerning privacy, and how they may
						pertain to you as a user of our website, products and subscriptions.</p>
				</div>
				<div className="mt-8">
					<p>
						This page informs you of our policies regarding the collection, use, and disclosure of
						personal data when you use our Service and the choices you have associated with that
						data.
					</p>
				</div>
				<div className="mt-8 border-b pb-40">
					<p>
						We use your data to provide and improve the Service. By using the Service, you agree to
						the collection and use of information in accordance with this policy. Unless otherwise
						defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings
						as in our Terms and Conditions, accessible from creationinternational.com
					</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">DEFINITIONS:</p>
					<ul>
						<li className="ml-2 mt-2"><strong>•</strong> ServiceService is the
							creationinternational.come website operated by Creation International.
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Personal DataPersonal Data means data about
							a living individual who can be identified from those data (or from those and other
							information either in our possession or likely to come into our possession).
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Usage DataUsage Data is data collected
							automatically either generated by the use of the Service or from the Service
							infrastructure itself (for example, the duration of a page visit).
							CookiesCookies are small pieces of data stored on your device (computer or mobile
							device).
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Data ControllerData Controller means the
							natural or legal person who (either alone or jointly or in common with other persons)
							determines the purposes for which and the manner in which any personal information
							are, or are to be, processed.For the purpose of this Privacy Policy, we are a Data
							Controller of your Personal Data.
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Data Processors (or Service Providers)Data
							Processor (or Service Provider) means any natural or legal person who processes the
							data on behalf of the Data Controller.We may use the services of various Service
							Providers in order to process your data more effectively.
						</li>
						<li className="ml-2 "><strong>•</strong> Data Subject (or User)Data Subject is any
							living individual who is using our Service and is the subject of Personal Data.
						</li>
					</ul>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">INFORMATION WE COLLECT AND USE</p>
				</div>
				<div className="py-8">
					<p>We collect several different types of information for various purposes to provide and
						improve our Service to you.</p>
				</div>
				<div>
					<p className="text-lg font-semibold">Personal Data</p>
				</div>
				<div className="mt-1">
					<p>While using our Service, we may ask you to provide us with certain personally
						identifiable information that can be used to contact or identify you (“Personal Data”).
						Personally identifiable information may include, but is not limited to:</p>
					<ul>
						<li className="ml-2 mt-2"><strong>•</strong> First name and last name</li>
						<li className="ml-2 mt-2"><strong>•</strong> Email address</li>
						<li className="ml-2 mt-2"><strong>•</strong> Phone number</li>
						<li className="ml-2 mt-2"><strong>•</strong> Business name</li>
						<li className="ml-2 mt-2"><strong>•</strong> Website URL</li>
						<li className="ml-2 mt-2"><strong>•</strong> Address, State, Province, ZIP/Postal code,
							City
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Any personal data you post on our website
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Any personal data you post on our website
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Data about how you use our website</li>
						<li className="ml-2 mt-2"><strong>•</strong> Technical data such as your IP address,
							your login data, details about your browser, time zone settings and other technology
							on the devise you use to access our website
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Your marketing and communication
							preferences
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Any information that you directly provide
							to us whether through our contact form ,over the phone, by email or otherwise
						</li>
						<li className="ml-2 mt-2"><strong>•</strong> Photographs of you at events</li>
						<li className="ml-2 mt-2"><strong>•</strong> Cookies and Usage Data</li>
					</ul>
					<p>We may use your Personal Data to contact you with newsletters, marketing or promotional
						materials and other information that may be of interest to you. You may opt out of
						receiving any, or all, of these communications from us by following the unsubscribe link
						or instructions provided in any email we send or by contacting us</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Usage Data</p>
				</div>
				<div className="mt-1">
					<p>We may also collect information how the Service is accessed and used (“Usage Data”).
						This Usage Data may include information such as your computer’s Internet Protocol
						address (e.g. IP address), browser type, browser version, the pages of our Service that
						you visit, the time and date of your visit, the time spent on those pages, unique device
						identifiers and other diagnostic data.</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Tracking & Cookies Data</p>
				</div>
				<div>
					<p>We use cookies and similar tracking technologies to track the activity on our Service
						and hold certain information.</p>
					<p>Cookies are files with small amount of data which may include an anonymous unique
						identifier. Cookies are sent to your browser from a website and stored on your device.
						Tracking technologies also used are beacons, tags, and scripts to collect and track
						information and to improve and analyze our Service.</p>
					<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is
						being sent. However, if you do not accept cookies, you may not be able to use some
						portions of our Service.</p>
					<p>Examples of Cookies we use:</p>
					<ul>
						<li className="ml-2 mt-1"><strong>•</strong> Session Cookies. We use Session Cookies to
							operate our Service.
						</li>
						<li className="ml-2 mt-1"><strong>•</strong> Preference Cookies. We use Preference
							Cookies to remember your preferences and various settings.
						</li>
						<li className="ml-2 mt-1"><strong>•</strong> Security Cookies. We use Security Cookies
							for security purposes.
						</li>
					</ul>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">USE OF DATA</p>
				</div>
				<div className="mt-4">
					<p>Creation International uses the collected data for various purposes:</p>
					<p>To provide and maintain our Service</p>
					<p>To notify you about changes to our Service</p>
					<p>To allow you to participate in interactive features of our Service when you choose to
						do so</p>
					<p>To provide customer support</p>
					<p>To gather analysis or valuable information so that we can improve our Service</p>
					<p>To monitor the usage of our Service</p>
					<p>To detect, prevent and address technical issues</p>
					<p>To provide you with news, special offers and general information about other goods,
						services and events which we offer that are similar to those that you have already
						purchased or enquired about unless you have opted not to receive such information.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">LEGAL BASIS FOR PROCESSING PERSONAL DATA UNDER
						GENERAL DATA PROTECTION REGULATION (GDPR)</p>
				</div>
				<div className="mt-4">
					<p>If you are from the European Economic Area (EEA), Creation International legal basis
						for collecting and using the personal information described in this Privacy Policy
						depends on the Personal Data we collect and the specific context in which we collect
						it.</p>
				</div>
				<div className="mt-4">
					<p>Creation International may process your Personal Data because:</p>
					<p>We need to perform a contract with you</p>
					<p>You have given us permission to do so</p>
					<p>The processing is in our legitimate interests and it’s not overridden by your
						rights</p>
					<p>For payment processing purposes</p>
					<p>To comply with the law</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">RETENTION OF DATA</p>
				</div>
				<div className="mt-4">
					<p>Creation International will retain your Personal Data only for as long as is necessary
						for the purposes set out in this Privacy Policy. We will retain and use your Personal
						Data to the extent necessary to comply with our legal obligations (for example, if we
						are required to retain your data to comply with applicable laws), resolve disputes, and
						enforce our legal agreements and policies.
					</p>
				</div>
				<div className="mt-4">
					<p>Creation International will also retain Usage Data for internal analysis purposes.
						Usage Data is generally retained for a shorter period of time, except when this data is
						used to strengthen the security or to improve the functionality of our Service, or we
						are legally obligated to retain this data for longer time periods.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">TRANSFER OF DATA</p>
				</div>
				<div className="mt-4">
					<p>Your information, including Personal Data, may be transferred to — and maintained on —
						computers located outside of your state, province, country or other governmental
						jurisdiction where the data protection laws may differ than those from your
						jurisdiction.
					</p>
					<p>If you are located outside United States and choose to provide information to us,
						please note that we transfer the data, including Personal Data, to United States and
						process it there.</p>
					<p>Your consent to this Privacy Policy followed by your submission of such information
						represents your agreement to that transfer.</p>
					<p>Creation International will take all steps reasonably necessary to ensure that your
						data is treated securely and in accordance with this Privacy Policy and no transfer of
						your Personal Data will take place to an organization or a country unless there are
						adequate controls in place including the security of your data and other personal
						information.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">DISCLOSURE OF DATA</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Business Transaction</p>
				</div>
				<div className="mt-2">
					<p>If Creation International is involved in a merger, acquisition or asset sale, your
						Personal Data may be transferred. We will provide notice before your Personal Data is
						transferred and becomes subject to a different Privacy Policy.</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Disclosure for Law Enforcement</p>
				</div>
				<div className="mt-2">
					<p>Under certain circumstances, Creation International may be required to disclose your
						Personal Data if required to do so by law or in response to valid requests by public
						authorities (e.g. a court or a government agency).</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Legal Requirements</p>
				</div>
				<div className="mt-2">
					<p>Creation International may disclose your Personal Data in the good faith belief that
						such action is necessary to:</p>
					<p>To comply with a legal obligation</p>
					<p>To protect and defend the rights or property of Creation International</p>
					<p>To prevent or investigate possible wrongdoing in connection with the Service</p>
					<p>To protect the personal safety of users of the Service or the public</p>
					<p>To protect against legal liability</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">SECURITY OF DATA</p>
				</div>
				<div className="mt-2">
					<p>The security of your data is important to us, but remember that no method of
						transmission over the Internet, or method of electronic storage is 100% secure. While we
						strive to use commercially acceptable means to protect your Personal Data, we cannot
						guarantee its absolute security.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">“DO NOT TRACK” SIGNALS</p>
				</div>
				<div className="mt-2">
					<p>We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in
						your web browser to inform websites that you do not want to be tracked.</p>
					<p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of
						your web browser.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">YOUR DATA PROTECTION RIGHTS UNDER GENERAL DATA
						PROTECTION REGULATION (GDPR)</p>
				</div>
				<div className="mt-2">
					<p>If you are a resident of the European Economic Area (EEA), you have certain data
						protection rights. Creation International aims to take reasonable steps to allow you to
						correct, amend, delete, or limit the use of your Personal Data.</p>
					<p>If you wish to be informed what Personal Data we hold about you and if you want it to
						be removed from our systems, please contact us.</p>
					<p>In certain circumstances, you have the following data protection rights:</p>
					<p>The right to access, update or to delete the information we have on you. Whenever made
						possible, you can access, update or request deletion of your Personal Data directly
						within your account settings section. If you are unable to perform these actions
						yourself, please contact us to assist you.</p>
					<p>The right of rectification. You have the right to have your information rectified if
						that information is inaccurate or incomplete.</p>
					<p>The right to object. You have the right to object to our processing of your Personal
						Data.</p>
					<p>The right of restriction. You have the right to request that we restrict the processing
						of your personal information.</p>
					<p>The right to data portability. You have the right to be provided with a copy of the
						information we have on you in a structured, machine-readable and commonly used
						format.</p>
					<p>The right to withdraw consent. You also have the right to withdraw your consent at any
						time where Creation International relied on your consent to process your personal
						information.</p>
					<p>Please note that we may ask you to verify your identity before responding to such
						requests.</p>
					<p>You have the right to complain to a Data Protection Authority about our collection and
						use of your Personal Data. For more information, please contact your local data
						protection authority in the European Economic Area (EEA).</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">SERVICE PROVIDERS</p>
				</div>
				<div className="mt-2">
					<p>We may employ third-party companies and individuals to facilitate our Service (“Service
						Providers”), to provide the Service on our behalf, to perform Service-related services
						or to assist us in analyzing how our Service is used.</p>
					<p>These third parties have access to your Personal Data only to perform these tasks on
						our behalf and are obligated not to disclose or use it for any other purpose.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">SERVICE PROVIDERS</p>
				</div>
				<div className="mt-2">
					<p>We may employ third-party companies and individuals to facilitate our Service (“Service
						Providers”), to provide the Service on our behalf, to perform Service-related services
						or to assist us in analyzing how our Service is used.</p>
					<p>These third parties have access to your Personal Data only to perform these tasks on
						our behalf and are obligated not to disclose or use it for any other purpose.</p>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Analytics</p>
				</div>
				<div className="mt-2">
					<p>We may use third-party Service Providers to monitor and analyze the use of our
						Service.</p>
					<ul>
						<li className="ml-2 mt-1"><strong>•</strong> Google AnalyticsGoogle Analytics is a web
							analytics service offered by Google that tracks and reports website traffic. Google
							uses the data collected to track and monitor the use of our Service. This data is
							shared with other Google services. Google may use the collected data to contextualize
							and personalize the ads of its own advertising network.You can opt-out of having made
							your activity on the Service available to Google Analytics by installing the Google
							Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript
							(ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about
							visits activity.For more information on the privacy practices of Google, please visit
							the Google Privacy & Terms web page: https://policies.google.com/privacy?hl=en
						</li>
					</ul>
				</div>
				<div className="mt-4">
					<p className="text-lg font-semibold">Behavioral Remarketing</p>
				</div>
				<div className="mt-2">
					<p>Creation International uses remarketing services to advertise on third party websites
						to you after you visited our Service. We and our third-party vendors use cookies to
						inform, optimize and serve ads based on your past visits to our Service.</p>
					<p>Google AdWordsGoogle AdWords remarketing service is provided by Google Inc.You can
						opt-out of Google Analytics for Display Advertising and customize the Google Display
						Network ads by visiting the Google Ads Settings page:
						https://www.google.com/settings/adsGoogle also recommends installing the Google
						Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your
						web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability
						to prevent their data from being collected and used by Google Analytics.For more
						information on the privacy practices of Google, please visit the Google Privacy & Terms
						web page: https://policies.google.com/privacy?hl=en</p>
					<p>practices of Google, please visit the Google Privacy & Terms web page:
						https://policies.google.com/privacy?hl=en
						TwitterTwitter remarketing service is provided by Twitter Inc.You can opt-out from
						Twitter’s interest-based ads by following their instructions:
						https://support.twitter.com/articles/20170405You can learn more about the privacy
						practices and policies of Twitter by visiting their Privacy Policy page:
						https://twitter.com/privacy</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">LINKS TO OTHER SITES</p>
				</div>
				<div className="mt-2">
					<p>Our Service may contain links to other sites that are not operated by us. If you click
						on a third party link, you will be directed to that third party’s site. We strongly
						advise you to review the Privacy Policy of every site you visit.</p>
					<p>We have no control over and assume no responsibility for the content, privacy policies
						or practices of any third party sites or services.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">CHILDREN’S PRIVACY</p>
				</div>
				<div className="mt-2">
					<p>Our Service does not address anyone under the age of 18 (“Children”).</p>
					<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
				</div>
				<div className="mt-24">
					<p className="text-2xl font-semibold">CHANGES TO THIS PRIVACY POLICY</p>
				</div>
				<div className="mt-2 pb-40">
					<p>We may update our Privacy Policy from time to time. We will notify you of any changes
						by posting the new Privacy Policy on this page.</p>
					<p>We will let you know via email and/or a prominent notice on our Service, prior to the
						change becoming effective and update the “effective date” at the top of this Privacy
						Policy.</p>
					<p>You are advised to review this Privacy Policy periodically for any changes. Changes to
						this Privacy Policy are effective when they are posted on this page.</p>
					<p>If you would like to: access, correct, amend or delete any personal information we have
						about you, register a complaint, or simply want more information contact our Privacy
						Compliance Officer at gabriela@creationinternational.com</p>
				</div>
			</div>
		</div>
		<Footer/>
		{isModalOpen && (
			<MenuModal isModalOpen={isModalOpen} onPress={toggleModal} />
		)}
	</div>;
}
